/**
* This is an autogenerated file created by the Stencil compiler.
* It contains typing information for all components that exist in this project.
*/
/* tslint:disable */

import '@stencil/core';




export namespace Components {

  interface SbCardBottom {}
  interface SbCardBottomAttributes extends StencilHTMLAttributes {}

  interface SbCardContent {}
  interface SbCardContentAttributes extends StencilHTMLAttributes {}

  interface SbCardHeader {}
  interface SbCardHeaderAttributes extends StencilHTMLAttributes {}

  interface SbCard {
    'sbClass': string;
  }
  interface SbCardAttributes extends StencilHTMLAttributes {
    'sbClass'?: string;
  }
}

declare global {
  interface StencilElementInterfaces {
    'SbCardBottom': Components.SbCardBottom;
    'SbCardContent': Components.SbCardContent;
    'SbCardHeader': Components.SbCardHeader;
    'SbCard': Components.SbCard;
  }

  interface StencilIntrinsicElements {
    'sb-card-bottom': Components.SbCardBottomAttributes;
    'sb-card-content': Components.SbCardContentAttributes;
    'sb-card-header': Components.SbCardHeaderAttributes;
    'sb-card': Components.SbCardAttributes;
  }


  interface HTMLSbCardBottomElement extends Components.SbCardBottom, HTMLStencilElement {}
  var HTMLSbCardBottomElement: {
    prototype: HTMLSbCardBottomElement;
    new (): HTMLSbCardBottomElement;
  };

  interface HTMLSbCardContentElement extends Components.SbCardContent, HTMLStencilElement {}
  var HTMLSbCardContentElement: {
    prototype: HTMLSbCardContentElement;
    new (): HTMLSbCardContentElement;
  };

  interface HTMLSbCardHeaderElement extends Components.SbCardHeader, HTMLStencilElement {}
  var HTMLSbCardHeaderElement: {
    prototype: HTMLSbCardHeaderElement;
    new (): HTMLSbCardHeaderElement;
  };

  interface HTMLSbCardElement extends Components.SbCard, HTMLStencilElement {}
  var HTMLSbCardElement: {
    prototype: HTMLSbCardElement;
    new (): HTMLSbCardElement;
  };

  interface HTMLElementTagNameMap {
    'sb-card-bottom': HTMLSbCardBottomElement
    'sb-card-content': HTMLSbCardContentElement
    'sb-card-header': HTMLSbCardHeaderElement
    'sb-card': HTMLSbCardElement
  }

  interface ElementTagNameMap {
    'sb-card-bottom': HTMLSbCardBottomElement;
    'sb-card-content': HTMLSbCardContentElement;
    'sb-card-header': HTMLSbCardHeaderElement;
    'sb-card': HTMLSbCardElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
