/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */

import '@stencil/core';

declare global {
  namespace JSX {
    interface Element {}
    export interface IntrinsicElements {}
  }
  namespace JSXElements {}

  interface HTMLElement {
    componentOnReady?: () => Promise<this | null>;
  }

  interface HTMLStencilElement extends HTMLElement {
    componentOnReady(): Promise<this>;

    forceUpdate(): void;
  }

  interface HTMLAttributes {}
}


declare global {

  namespace StencilComponents {
    interface SunbirdCard {
      'cardButtonName': string;
      'cardButtonUrl': string;
      'cardDescription': string;
      'cardImage': string;
      'cardProgress': number;
      'cardTitle': string;
    }
  }

  interface HTMLSunbirdCardElement extends StencilComponents.SunbirdCard, HTMLStencilElement {}

  var HTMLSunbirdCardElement: {
    prototype: HTMLSunbirdCardElement;
    new (): HTMLSunbirdCardElement;
  };
  interface HTMLElementTagNameMap {
    'sunbird-card': HTMLSunbirdCardElement;
  }
  interface ElementTagNameMap {
    'sunbird-card': HTMLSunbirdCardElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'sunbird-card': JSXElements.SunbirdCardAttributes;
    }
  }
  namespace JSXElements {
    export interface SunbirdCardAttributes extends HTMLAttributes {
      'cardButtonName'?: string;
      'cardButtonUrl'?: string;
      'cardDescription'?: string;
      'cardImage'?: string;
      'cardProgress'?: number;
      'cardTitle'?: string;
    }
  }
}

declare global { namespace JSX { interface StencilJSX {} } }

export declare function defineCustomElements(window: any): void;