/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */

import '@stencil/core';

declare global {
  namespace JSX {
    interface Element {}
    export interface IntrinsicElements {}
  }
  namespace JSXElements {}

  interface HTMLElement {
    componentOnReady?: () => Promise<this | null>;
  }

  interface HTMLStencilElement extends HTMLElement {
    componentOnReady(): Promise<this>;

    forceUpdate(): void;
  }

  interface HTMLAttributes {}
}


declare global {

  namespace StencilComponents {
    interface SunbirdCardComponent {
      'cardbuttonname': string;
      'cardbuttonurl': string;
      'carddescription': string;
      'cardimage': string;
      'cardprogress': number;
      'cardtitle': string;
    }
  }

  interface HTMLSunbirdCardComponentElement extends StencilComponents.SunbirdCardComponent, HTMLStencilElement {}

  var HTMLSunbirdCardComponentElement: {
    prototype: HTMLSunbirdCardComponentElement;
    new (): HTMLSunbirdCardComponentElement;
  };
  interface HTMLElementTagNameMap {
    'sunbird-card-component': HTMLSunbirdCardComponentElement;
  }
  interface ElementTagNameMap {
    'sunbird-card-component': HTMLSunbirdCardComponentElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'sunbird-card-component': JSXElements.SunbirdCardComponentAttributes;
    }
  }
  namespace JSXElements {
    export interface SunbirdCardComponentAttributes extends HTMLAttributes {
      'cardbuttonname'?: string;
      'cardbuttonurl'?: string;
      'carddescription'?: string;
      'cardimage'?: string;
      'cardprogress'?: number;
      'cardtitle'?: string;
    }
  }
}

declare global { namespace JSX { interface StencilJSX {} } }

export declare function defineCustomElements(window: any): void;